### ISSUE TITLE
[BUG] Dependencu issue with forge 1.20.2

### ISSUE THREAD

**Issue by Lennart99** [KevinDaGame/VoxelSniper-Reimagined#240]
**Describe the bug**

**To Reproduce**
1. Install forge client - I used forge-1.20.2-48.1.0
2. Install the voxelsniper mod (used v8.13.0)
3. Try to start the client
4. Client crashes

**Expected behavior**
No crash

**Screenshots**

**Desktop (please complete the following information):**
 - Minecraft version: 1.20.2
 - Voxelsniper version: 8.13.0
 - Server/client software: Forge 1.20.2-48.1.0

**Additional context**

**server log/crash report**
Add your log file here, this helps us see what's wrong

`17:55:33.923
game
[17:55:33] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
17:55:34.932
game
Exception in thread "main" java.lang.module.ResolutionException: Modules voxelsniperforge and org.slf4j export package org.slf4j.event to module forge
17:55:34.932
game
at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
17:55:34.932
game
at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
17:55:34.932
game
at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
17:55:34.932
game
at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
17:55:34.932
game
at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
17:55:34.932
game
at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
17:55:34.932
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:72)
17:55:34.932
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:47)
17:55:34.932
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:94)
17:55:34.932
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
17:55:34.932
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13)
17:55:34.932
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10)
17:55:34.933
game
at net.minecraftforge.bootstrap@1.2.0/net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126)
17:55:35.064
monitor
Process Monitor
Process crashed with exit code 1`

**Comment by Vrath** [comment]
it also crashes with fabric
